/**
 * @file      http_utils.cpp
 * @author    LilyGo
 * @license   MIT
 * @copyright Copyright (c) 2025  ShenZhen XinYuan Electronic Technology Co., Ltd
 * @date      2025-04-01
 * @brief     Shared HTTPS request utilities implementation.
 */
#include "http_utils.h"

#ifdef ARDUINO
#include <WiFi.h>
#include <WiFiClientSecure.h>
#include <HTTPClient.h>
#include <mbedtls/base64.h>
#include <esp_heap_caps.h>

/* Full Mozilla root-CA bundle in the esp_crt_bundle binary format
 * (GENERATED by scripts/gen_ca_bundle.py from curl.se/cacert.pem - don't
 * hand-edit). Covers every public provider endpoint; no per-provider root
 * additions needed. Consumed in place from flash: the core keeps only a
 * pointer index in heap and binary-searches subject names at handshake. */
#include "ca_bundle_full.h"

static http_tls_mode_t s_tls_mode = HTTP_TLS_CA_VERIFY;

void http_set_tls_mode(http_tls_mode_t mode) { s_tls_mode = mode; }
http_tls_mode_t http_get_tls_mode(void) { return s_tls_mode; }

/* Configure a WiFiClientSecure instance per the current TLS mode.
 * Exported (additive) for penpal_api's own https transport - see header.
 * Replaces the former hand-picked PEM bundle (reviewer #2 fix era): with
 * setCACert every HTTPS client parsed ALL bundled certs into a heap chain
 * per request; the esp_crt_bundle path anchors via the flash-resident
 * bundle and parses only the one matching public key (device finding
 * 2026-08-28: deepseek/minimax chains had no anchor in the 8-root pick). */
void http_apply_tls(WiFiClientSecure &client)
{
    if (s_tls_mode == HTTP_TLS_INSECURE) {
        client.setInsecure();
    } else {
        client.setCACertBundle(CA_BUNDLE_MOZILLA);
    }
}

bool http_require_wifi(const char *feature_name)
{
    return WiFi.status() == WL_CONNECTED;
}

/* TLS cert validation needs a sane system clock; pool.ntp.org is often
 * unreachable in CN networks, so prefer cn.pool.ntp.org and fail requests
 * with a clear message instead of a generic TLS verify error. */
bool http_ensure_time(uint32_t max_wait_ms)
{
    if (time(nullptr) > 1700000000) {           /* after 2023-11-14 */
        return true;
    }
    Serial.println("[HTTP] system time not synced - requesting NTP");
    configTzTime("CST-8", "cn.pool.ntp.org", "pool.ntp.org", "time.nist.gov");
    uint32_t t0 = millis();
    while (time(nullptr) <= 1700000000 && millis() - t0 < max_wait_ms) {
        delay(100);
    }
    bool ok = (time(nullptr) > 1700000000);
    Serial.printf("[HTTP] NTP retry %s (epoch=%ld)\n", ok ? "ok" : "failed", (long)time(nullptr));
    return ok;
}

static void http_capture_error(http_response_t &resp, HTTPClient &http,
                               WiFiClientSecure &client)
{
    char err[128] = {0};
    client.lastError(err, sizeof(err));
    if (err[0] != '\0') {
        resp.error = err;
    } else {
        resp.error = http.errorToString(resp.status_code).c_str();
    }
}

http_response_t http_get(const char *url, uint32_t timeout_ms)
{
    return http_get_ua(url, NULL, timeout_ms);
}

http_response_t http_get_ua(const char *url, const char *user_agent, uint32_t timeout_ms)
{
    http_response_t resp = {0, "", false, ""};
    if (s_tls_mode != HTTP_TLS_INSECURE && !http_ensure_time(5000)) {
        resp.status_code = -3;
        resp.error = "Time not synced - retry after NTP";
        resp.body = resp.error;
        return resp;
    }
    WiFiClientSecure client;
    http_apply_tls(client);
    HTTPClient http;

    http.setTimeout(timeout_ms);
    if (!http.begin(client, url)) {
        resp.body = (s_tls_mode == HTTP_TLS_INSECURE) ? "Failed to connect" : "Failed to connect (TLS)";
        char err[128] = {0};
        client.lastError(err, sizeof(err));
        resp.error = err[0] ? err : resp.body;
        return resp;
    }

    if (user_agent && user_agent[0] != '\0') {
        http.addHeader("User-Agent", user_agent);
    }

    resp.status_code = http.GET();
    if (resp.status_code > 0) {
        resp.body = http.getString().c_str();
        resp.success = (resp.status_code >= 200 && resp.status_code < 300);
    } else {
        resp.body = http.errorToString(resp.status_code).c_str();
        http_capture_error(resp, http, client);
    }
    http.end();
    return resp;
}

http_response_t http_get_auth(const char *url, const char *auth_header, uint32_t timeout_ms)
{
    http_response_t resp = {0, "", false, ""};
    if (s_tls_mode != HTTP_TLS_INSECURE && !http_ensure_time(5000)) {
        resp.status_code = -3;
        resp.error = "Time not synced - retry after NTP";
        resp.body = resp.error;
        return resp;
    }
    WiFiClientSecure client;
    http_apply_tls(client);
    HTTPClient http;

    http.setTimeout(timeout_ms);
    if (!http.begin(client, url)) {
        resp.body = (s_tls_mode == HTTP_TLS_INSECURE) ? "Failed to connect" : "Failed to connect (TLS)";
        char err[128] = {0};
        client.lastError(err, sizeof(err));
        resp.error = err[0] ? err : resp.body;
        return resp;
    }

    if (auth_header && auth_header[0] != '\0') {
        http.addHeader("Authorization", auth_header);
    }

    resp.status_code = http.GET();
    if (resp.status_code > 0) {
        resp.body = http.getString().c_str();
        resp.success = (resp.status_code >= 200 && resp.status_code < 300);
    } else {
        resp.body = http.errorToString(resp.status_code).c_str();
        http_capture_error(resp, http, client);
    }
    http.end();
    return resp;
}

http_response_t http_post_with_headers(const char *url, const string &body,
                                       const char *content_type,
                                       const char *auth_header,
                                       const char *header_names[],
                                       const char *header_values[],
                                       int header_count,
                                       uint32_t timeout_ms)
{
    http_response_t resp = {0, "", false, ""};
    if (s_tls_mode != HTTP_TLS_INSECURE && !http_ensure_time(5000)) {
        resp.status_code = -3;
        resp.error = "Time not synced - retry after NTP";
        resp.body = resp.error;
        return resp;
    }
    WiFiClientSecure client;
    http_apply_tls(client);
    HTTPClient http;

    http.setTimeout(timeout_ms);
    http.useHTTP10(true);                           /* force HTTP/1.0 to avoid
        chunked encoding / keep-alive body-read issues with some providers */
    if (!http.begin(client, url)) {
        resp.body = (s_tls_mode == HTTP_TLS_INSECURE) ? "Failed to connect" : "Failed to connect (TLS)";
        char err[128] = {0};
        client.lastError(err, sizeof(err));
        resp.error = err[0] ? err : resp.body;
        return resp;
    }

    http.addHeader("Content-Type", content_type);
    /* header() only returns collected headers - without collectHeaders() the
     * Content-Type/Content-Encoding diagnostics below always logged empty. */
    static const char *s_resp_hdrs[] = { "Content-Type", "Content-Encoding" };
    http.collectHeaders(s_resp_hdrs, 2);
    http.addHeader("Accept-Encoding", "identity");  /* ESP32 HTTPClient does not
        decompress gzip; force uncompressed responses (OpenRouter etc.). */
    http.addHeader("Connection", "close");          /* help HTTPClient detect
        end-of-body on slow/chunked responses (DeepSeek read timeout). */
    if (auth_header && auth_header[0] != '\0') {
        http.addHeader("Authorization", auth_header);
    }
    for (int i = 0; i < header_count; i++) {
        if (header_names[i] && header_names[i][0] != '\0' &&
            header_values[i] && header_values[i][0] != '\0') {
            http.addHeader(header_names[i], header_values[i]);
        }
    }

    resp.status_code = http.POST(body.c_str());
    if (resp.status_code > 0) {
        Serial.printf("[HTTP] status=%d ct=%s ce=%s\n",
                      resp.status_code,
                      http.header("Content-Type").c_str(),
                      http.header("Content-Encoding").c_str());
        resp.body = http.getString().c_str();
        resp.success = (resp.status_code >= 200 && resp.status_code < 300);
    } else {
        resp.body = http.errorToString(resp.status_code).c_str();
        http_capture_error(resp, http, client);
    }
    http.end();
    return resp;
}

http_response_t http_post(const char *url, const string &body,
                          const char *content_type,
                          const char *auth_header,
                          uint32_t timeout_ms)
{
    return http_post_with_headers(url, body, content_type, auth_header,
                                  NULL, NULL, 0, timeout_ms);
}

http_response_t http_post_large(const char *url, const uint8_t *data, size_t data_len,
                                const char *content_type, uint32_t timeout_ms)
{
    http_response_t resp = {0, "", false, ""};
    if (s_tls_mode != HTTP_TLS_INSECURE && !http_ensure_time(5000)) {
        resp.status_code = -3;
        resp.error = "Time not synced - retry after NTP";
        resp.body = resp.error;
        return resp;
    }
    WiFiClientSecure client;
    http_apply_tls(client);
    HTTPClient http;

    http.setTimeout(timeout_ms);
    if (!http.begin(client, url)) {
        resp.body = (s_tls_mode == HTTP_TLS_INSECURE) ? "Failed to connect" : "Failed to connect (TLS)";
        char err[128] = {0};
        client.lastError(err, sizeof(err));
        resp.error = err[0] ? err : resp.body;
        return resp;
    }

    http.addHeader("Content-Type", content_type);

    resp.status_code = http.sendRequest("POST", (uint8_t *)data, data_len);
    if (resp.status_code > 0) {
        resp.body = http.getString().c_str();
        resp.success = (resp.status_code >= 200 && resp.status_code < 300);
    } else {
        resp.body = http.errorToString(resp.status_code).c_str();
        http_capture_error(resp, http, client);
    }
    http.end();
    return resp;
}

char *base64_encode_psram(const uint8_t *data, size_t len, size_t *out_len)
{
    size_t encoded_len = 0;
    mbedtls_base64_encode(NULL, 0, &encoded_len, data, len);

    char *encoded = (char *)heap_caps_malloc(encoded_len + 1, MALLOC_CAP_SPIRAM | MALLOC_CAP_8BIT);
    if (!encoded) {
        *out_len = 0;
        return NULL;
    }

    mbedtls_base64_encode((unsigned char *)encoded, encoded_len + 1, &encoded_len, data, len);
    encoded[encoded_len] = '\0';
    *out_len = encoded_len;
    return encoded;
}

#else
// Desktop stubs
class WiFiClientSecure;   /* reference param only */
void http_set_tls_mode(http_tls_mode_t mode) {}
http_tls_mode_t http_get_tls_mode(void) { return HTTP_TLS_INSECURE; }
bool http_require_wifi(const char *feature_name) { return false; }
void http_apply_tls(WiFiClientSecure &client) {}
bool http_ensure_time(uint32_t max_wait_ms) { return true; }
http_response_t http_get(const char *url, uint32_t timeout_ms) { return {0, "Not supported on desktop", false, ""}; }
http_response_t http_get_ua(const char *url, const char *user_agent, uint32_t timeout_ms) { return {0, "Not supported on desktop", false, ""}; }
http_response_t http_get_auth(const char *url, const char *auth_header, uint32_t timeout_ms) { return {0, "Not supported on desktop", false, ""}; }
http_response_t http_post(const char *url, const string &body, const char *content_type, const char *auth_header, uint32_t timeout_ms) { return {0, "Not supported on desktop", false, ""}; }
http_response_t http_post_large(const char *url, const uint8_t *data, size_t data_len, const char *content_type, uint32_t timeout_ms) { return {0, "Not supported on desktop", false, ""}; }
char *base64_encode_psram(const uint8_t *data, size_t len, size_t *out_len) { *out_len = 0; return NULL; }
#endif
