#!/usr/bin/env python3
"""Generate examples/pda2/src/img_penpal.c - the PenPal menu icon (envelope).

Byte format matches the existing img_*.c icons in examples/pda2/src/
(LV_IMG_CF_TRUE_COLOR_ALPHA at LV_COLOR_DEPTH=1 -> 2 bytes per pixel:
color byte first, alpha byte second; ink = 0x00,0xff black-opaque,
empty = 0x00,0x00).  Verify the convention any time with --inspect.

Usage (run from the repo root):
  python scripts/gen_img_penpal.py                     # write the .c file
  python scripts/gen_img_penpal.py --preview           # ASCII art only
  python scripts/gen_img_penpal.py --inspect examples/pda2/src/img_dictionary.c
"""
import argparse
import re
import sys
from pathlib import Path

W = H = 50
OUT = Path(__file__).resolve().parent.parent / "examples/pda2/src/img_penpal.c"


# ---------------------------------------------------------------- raster
class Canvas:
    def __init__(self):
        self.px = [[0] * W for _ in range(H)]

    def dot(self, x, y, t):
        for dy in range(t):
            for dx in range(t):
                xx, yy = x + dx, y + dy
                if 0 <= xx < W and 0 <= yy < H:
                    self.px[yy][xx] = 1

    def line(self, x0, y0, x1, y1, t=2):
        """Bresenham line with a t*t brush."""
        dx, dy = abs(x1 - x0), -abs(y1 - y0)
        sx = 1 if x0 < x1 else -1
        sy = 1 if y0 < y1 else -1
        err = dx + dy
        while True:
            self.dot(x0, y0, t)
            if x0 == x1 and y0 == y1:
                break
            e2 = 2 * err
            if e2 >= dy:
                err += dy
                x0 += sx
            if e2 <= dx:
                err += dx
                y0 += sy

    def _rrect_mask(self, x0, y0, x1, y1, r):
        for y in range(max(y0, 0), min(y1, H - 1) + 1):
            for x in range(max(x0, 0), min(x1, W - 1) + 1):
                cx = min(max(x, x0 + r), x1 - r)
                cy = min(max(y, y0 + r), y1 - r)
                dx, dy = x - cx, y - cy
                if dx * dx + dy * dy <= r * r:
                    yield x, y

    def rrect_border(self, x0, y0, x1, y1, r=4, t=2):
        """Outlined rounded rect: filled outer minus filled inner."""
        inner = set(self._rrect_mask(x0 + t, y0 + t, x1 - t, y1 - t,
                                     max(r - t, 0)))
        for x, y in self._rrect_mask(x0, y0, x1, y1, r):
            if (x, y) not in inner:
                self.px[y][x] = 1


def draw_envelope():
    c = Canvas()
    # envelope body: 2px rounded border, centered like the other icons
    c.rrect_border(5, 8, 44, 42, r=4, t=2)
    # flap: both top corners converging on the middle
    c.line(8, 12, 23, 28, 2)
    c.line(41, 12, 26, 28, 2)
    return c


# ---------------------------------------------------------------- output
def render_lines(c):
    for row in c.px:
        yield "  " + ", ".join(
            "0x00, 0xff" if v else "0x00, 0x00" for v in row) + ","


def write_c_file(c):
    body = "\n".join(render_lines(c))
    OUT.write_text(
        '#include "lvgl.h"\n'
        "/* PenPal menu icon - envelope.\n"
        " * Generated by scripts/gen_img_penpal.py - edit that script, not\n"
        " * this file. 2 bytes/pixel: (color, alpha), ink = 0x00,0xff\n"
        " * (black opaque), 0x00,0x00 = transparent (LV_COLOR_DEPTH=1). */\n"
        "const LV_ATTRIBUTE_MEM_ALIGN uint8_t img_penpal_map[] = {\n"
        f"{body}\n"
        "};\n"
        "const lv_img_dsc_t img_penpal = {\n"
        "  .header.always_zero = 0, .header.w = 50, .header.h = 50,\n"
        "  .data_size = 2500 * LV_IMG_PX_SIZE_ALPHA_BYTE,\n"
        "  .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA, .data = img_penpal_map,\n"
        "};\n",
        encoding="utf-8")
    print(f"wrote {OUT}")


def preview(c):
    for y, row in enumerate(c.px):
        print(f"{y:2d} " + "".join("#" if v else " " for v in row))


def inspect(path):
    """Decode an existing img_*.c and print it - documents the format."""
    src = Path(path).read_text(encoding="utf-8")
    m = re.search(r"_map\[\] = \{(.*?)\};", src, re.S)
    vals = [int(x, 16) for x in re.findall(r"0x([0-9a-fA-F]{2})", m.group(1))]
    if len(vals) != W * H * 2:
        sys.exit(f"unexpected size: {len(vals)} bytes")
    for y in range(H):
        line = ""
        for x in range(W):
            col, alpha = vals[(y * W + x) * 2:(y * W + x) * 2 + 2]
            line += " " if alpha == 0 else ("#" if col == 0 else ".")
        print(f"{y:2d} {line}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--preview", action="store_true",
                    help="print ASCII art instead of writing the file")
    ap.add_argument("--inspect", metavar="IMG_C",
                    help="decode an existing img_*.c and print it")
    args = ap.parse_args()
    if args.inspect:
        inspect(args.inspect)
        return
    c = draw_envelope()
    if args.preview:
        preview(c)
    else:
        write_c_file(c)


if __name__ == "__main__":
    main()
