#!/usr/bin/env python3
"""One-time OTA keypair generator (docs/ota-update-design.md §2.2).

Generates a P-256 keypair for manifest signing:
  - ota_signing_key.pem   (repo root, GITIGNORED - the private key)
  - examples/pda2/ota_trust_anchor.h (tracked - 65 B uncompressed SEC1
    public point + key_id for diagnostics only)

Re-running REGENERATES both; devices only trust the old anchor until they
are reflashed over USB (换根仅 USB, §2.2).
"""
import datetime
import pathlib

from cryptography.hazmat.primitives.asymmetric import ec
from cryptography.hazmat.primitives.serialization import (
    Encoding, NoEncryption, PrivateFormat, PublicFormat)

ROOT = pathlib.Path(__file__).resolve().parents[1]
KEY = ROOT / "ota_signing_key.pem"
HDR = ROOT / "examples" / "pda2" / "ota_trust_anchor.h"

key = ec.generate_private_key(ec.SECP256R1())
KEY.write_bytes(key.private_bytes(
    Encoding.PEM, PrivateFormat.PKCS8, NoEncryption()))
sec1 = key.public_key().public_bytes(
    Encoding.X962, PublicFormat.UncompressedPoint)
assert len(sec1) == 65 and sec1[0] == 0x04

key_id = f"{int.from_bytes(sec1[-4:], 'big'):08X}"   # last 4 bytes, diag only
rows = []
for i in range(0, 65, 12):
    rows.append("    " + ", ".join(f"0x{b:02X}" for b in sec1[i:i + 12]) + ",")
HDR.write_text(
    "/**\n"
    " * GENERATED by scripts/ota_gen_key.py - do not edit by hand.\n"
    " * OTA manifest trust anchor: P-256 public point, 65 B uncompressed\n"
    " * SEC1 (docs/ota-update-design.md §2.2). The matching private key\n"
    " * lives ONLY in the gitignored ota_signing_key.pem. Key rotation is\n"
    f" * USB-only. key_id is diagnostics, not security ({key_id}).\n"
    f" * Created: {datetime.date.today().isoformat()}\n"
    " */\n"
    "#pragma once\n"
    "#include <stdint.h>\n"
    "#define OTA_TRUST_KEY_ID \"" + key_id + "\"\n"
    "static const uint8_t OTA_TRUST_ANCHOR_SEC1[65] = {\n"
    + "\n".join(rows) + "\n};\n",
    encoding="utf-8", newline="\n")
print(f"wrote {KEY.name} (private, gitignored) and {HDR.relative_to(ROOT)}")
print(f"public SEC1: {sec1.hex()}")
